import random
#Valores iniciales magizoologos
SICKLES_INICIAL = 500
LICENCIA = True
HABILIDAD = True
MAGIA_DOCENCIO = random.randint(40, 60)
DESTREZA_DOCENCIO = random.randint(30, 40)
ENERGIA_DOCENCIO = random.randint(40, 50)
RESPONSABILIDAD_DOCENCIO = random.randint(15, 20)
MAGIA_TAREO = random.randint(40, 55)
DESTREZA_TAREO = random.randint(40, 50)
ENERGIA_TAREO = random.randint(35, 45)
RESPONSABILIDAD_TAREO = random.randint(10, 25)
MAGIA_HIBRIDO = random.randint(35, 45)
DESTREZA_HIBRIDO = random.randint(30, 50)
ENERGIA_HIBRIDO = random.randint(50, 55)
RESPONSABILIDAD_HIBRIDO = random.randint(15, 25)
ENERGIA_ALIMENTAR = 5
ENERGIA_RECUPERAR = 10
ENERGIA_SANAR = 8
#Menu DCC
APROBACION_MIN = 60
APUESTA = 30
ATAQ_INOF = 0.25
ATAQ_ARISCA = 0.3  
ATAQ_PELIGROSA = 0.35
ESQUIVAR = 0.5
#Multas DCC
DCC_ESCAPE = 50
DCC_ENFERMEDAD = 70
DCC_BAJA_SALUD = 150
COSTO_AUGUREY = 75
COSTO_NIFFLER = 100
COSTO_ERKLING = 125
COSTO_TARTA = 10
COSTO_HIGADO = 15
COSTO_BUÑUELOS = 3
SALUD_TARTA = 15
SALUD_HIGADO = 10
SALUD_BUÑUELO = 10
#Alimentar
ALIMENTO_DOCENCIO = 5
ALIMENTO_HIBRIDO = 10
#Ataque
EFECTO_HAMBRE_HAMBRIENTA = 15
EFECTO_AGRESIVIDAD_ARISCA = 20
EFECTO_AGRESIVIDAD_PELIGROSA = 40
#Cambio de dia 
ENFERMA_DIA = 7
HAMBRE_DIA = 3
#Valores iniciales Criaturas
MAGIA_AUGUREY = random.randint(20, 25)
ESCAPE_AUGUREY = 0.2
ENFERMIZA_AUGUREY = 0.3
SALUD_AUGUREY = random.randint(35, 45)
AGRESIVIDAD_AUGUREY = "inofensiva"
MAGIA_NIFFLER = random.randint(10, 20)
ESCAPE_NIFFLER = 0.3
ENFERMIZA_NIFFLER = 0.2
SALUD_NIFFLER = random.randint(20, 30)
AGRESIVIDAD_NIFFLER = "arisca"
CLEP_NIFFLER = random.randint(5, 10)
MAGIA_ERKLING = random.randint(30, 45)
ESCAPE_ERKLING = 0.5
ENFERMIZA_ERKLING = 0.3
SALUD_ERKLING = random.randint(50, 60)
AGRESIVIDAD_ERKLING = "peligrosa"
ENFERMA_NUEVA = "False"
FUGITIVA_NUEVA = "False"
HAMBRE_NEW = "satisfecha"
DIAS_SIN_C_NEW = 0
CLEP_AUG_ERK = 0
#Rutas archivos
RUTA_MAGIZOOLOGOS = "magizoologos.csv"
RUTA_CRIAT = "criaturas.csv"